<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QKUP3QK" failures="1" tests="3" name="Testing.LoginTest" time="0.798" errors="0" timestamp="2025-05-17T17:08:04 IST" skipped="0">
  <testcase classname="Testing.LoginTest" name="loginpageTitleTest" time="0.032">
    <system-out>
      <![CDATA[Method name is -loginpageTitleTest
Status of exceusion is -1]]>
    </system-out>
  </testcase> <!-- loginpageTitleTest -->
  <testcase classname="Testing.LoginTest" name="TekskillsLogoTest" time="0.056">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Testing.LoginTest.TekskillsLogoTest(LoginTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Method name is -TekskillsLogoTest
<a href ="D:\Selenium data\OnboardingProcess-HRA\test-output\">Test result </a>]]>
    </system-out>
  </testcase> <!-- TekskillsLogoTest -->
  <testcase classname="Testing.LoginTest" name="logintest" time="0.710">
    <system-out>
      <![CDATA[Method name is -logintest
Status of exceusion is -1]]>
    </system-out>
  </testcase> <!-- logintest -->
  <system-out>
    <![CDATA[Method name is -loginpageTitleTest
Status of exceusion is -1
Method name is -TekskillsLogoTest
<a href ="D:\Selenium data\OnboardingProcess-HRA\test-output\">Test result </a>
Method name is -logintest
Status of exceusion is -1
Method name is -fillEmploymentDetailsTest
<a href ="D:\Selenium data\OnboardingProcess-HRA\test-output\">Test result </a>]]>
  </system-out>
</testsuite> <!-- Testing.LoginTest -->
